config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  root 'bikes#index'
  resources :categories, only: [:index, :show]
  resources :orders, only: [:index]
  resources :reviews, only: [:index]
  # resources :saved_bike, only: [:index]
  resources :bikes do
    resources :orders, only: [:new, :create]
    resources :reviews, only: [:new, :create]
    resource :saved_bike, only: [:index, :create, :destroy]
  end
  get '/saved', to: 'pages#saved'
  get '/contact', to: 'contacts#new', as: 'contact'
  post '/contact', to: 'contacts#create'
  get '/about', to: 'pages#about'
  get '/privacy_policy', to: 'pages#privacy_policy'
  get '/return_and_refund', to: 'pages#return_and_refund'
  get '/terms_and_conditions', to: 'pages#terms_and_conditions'
  get '/orders/:id/confirmation', to: 'orders#confirmation', as: 'order_confirmation'
  get 'feed/google', to: 'feed#google', defaults: { format: 'xml' }
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bike.rb
class Bike < ApplicationRecord
  extend FriendlyId
  friendly_id :model, use: :slugged

  belongs_to :category
  belongs_to :brand, optional: true
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :saved_bikes, dependent: :destroy
  has_many :users, through: :saved_bikes
  include PgSearch::Model

  enum registration_status: { registered: 0, unregistered: 1 }
  has_many_attached :photos

  pg_search_scope :global_search,
  against: :model,
  associated_against: {
    category: :name,
    brand: :name
  },
  using: {
    tsearch: { prefix: true } # Allows partial matching, e.g., "mount" matches "mountain"
  }

  # validates :model, :kilometers, :body, :colour, :engine_capacity, :price, :description, :features, :maximum_speed, :fuel_type, presence: true
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: %i[show edit update destroy]
  before_action :strong_params, only: %i[create update]
  before_action :authorize_admin, only: %i[new edit destroy]
  def index
    if params[:query].present?
      @bikes = Bike.global_search(params[:query]).limit(8)

      @scroll_to_bikes = true
    else
      @bikes = Bike.order("RANDOM()").limit(8)
    end
    @categories = Category.all
    @brands = Brand.all
    @reviews = Review.all.limit(4)
    @articles = Article.all.limit(6)
    @e_bikes = Bike.joins(:category).where(categories: { name: "Electric" }).order(created_at: :desc).limit(4)
  end

  def show
    @order = Order.new(bike: @bike)
  end

  def new
    @bike = Bike.new(params[:bike])
  end

  def create
    @bike = Bike.new(strong_params)
    if @bike.save
      redirect_to bike_path(@bike), notice: "Bike was successfully updated."
    else
      render :new
    end
  end

  def edit
  end

  def update
    # if @bike.update(strong_params)
    #   redirect_to bike_path(@bike), notice: "Bike was successfully updated."
    # # else
    # #   render :edit
    # end
    # if strong_params[:photos].present?
    #   @bike.photos.attach(strong_params[:photos])
    # end
    if strong_params[:photos].present?
      # Update photos and other attributes separately
      if @bike.update(strong_params.except(:photos)) && @bike.photos.attach(strong_params[:photos])
        redirect_to bike_path(@bike), notice: "Bike and photos were successfully updated."
      else
        render :edit
      end
    else
      # No photos to update, just update other attributes
      if @bike.update(strong_params.except(:photos))
        redirect_to bike_path(@bike), notice: "Bike was successfully updated."
      else
        render :edit
      end
    end

  end


  def destroy
    if @bike.destroy
      redirect_to bikes_path, status: :see_other, notice: "Bike was successfully deleted."
    else
      flash[:alert] = "Bike cannot be deleted due to associated category or brand."
      redirect_to bikes_path
    end
  end

  def create_order
    @bike = Bike.friendly.find(params[:bike_id])  # Get the bike from params
    @order = @bike.orders.new(order_params)

    if @order.save
      redirect_to @bike, notice: 'Order was successfully created.'
    else
      render :show  # Render the show page again in case of errors
    end
  end

  private
  def set_bike
    @bike = Bike.friendly.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:name, :email, :phone, :quantity)
  end

  def strong_params
    @bikes = params.require(:bike).permit(:model, :kilometers, :body, :colour, :engine_capacity, :last_modified, :registration_status, :description,
    :features, :price, :stock, :maximum_speed, :fuel_type, :category_id, :brand_id, photos: [] )
  end

  def authorize_admin
    redirect_to root_path, alert: "Not authorized!" unless current_user&.admin?
  end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/edit.html.erb
<h2 class="form-title">Edit Bikes details</h2>

<%= simple_form_for @bike,
    local: true,
    data: { controller: "loading", action: "submit->loading#showSpinner" },
    html: { class: "custom-bike-form" } do |form| %>
  <div class="form-group">
    <%= form.input :model, placeholder: "Enter bike model", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :kilometers, placeholder: "Enter kilometers traveled", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :body, placeholder: "Enter purpose or type of bike", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :colour, placeholder: "Enter color", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :engine_capacity, placeholder: "Enter engine capacity in cc", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :last_modified, as: :date, label: false, placeholder: "Select last modified date" %>
  </div>
  <div class="form-group">
    <%= form.input :registration_status,
                  as: :select,
                  collection: Bike.registration_statuses.keys,
                  prompt: "Enter registration status",
                  label: false %>
  </div>
  </div>
  <div class="form-group">
    <%= form.input :description, placeholder: "Enter a brief description", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :features, placeholder: "List features separated by commas", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :price, placeholder: "Enter price in currency", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :maximum_speed, placeholder: "Enter maximum speed in km/h", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :fuel_type, placeholder: "Enter fuel type (e.g., petrol, electric)", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :make, placeholder: "Enter Make", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :category_id, as: :select, collection: Category.all, prompt: "Select a Category", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :brand_id, as: :select, collection: Brand.all, prompt: "Select a Brand", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :photos, as: :file, input_html: { multiple: true }, label: false %>
  </div>
  <div class="form-group submit-button">
    <%= form.button :submit, "Save Bike Info" %>
  </div>
  <span class="loader text-center" data-loading-target="spinner" style="display: none;"></span>
<% end %>

app/views/bikes/index.html.erb
<section class="hero">
  <div class="hero-text">
    <h1>Looking to Purchase Bikes with Unmatched Quality?</h1>
    <p>Find the best ATVs for sale, including the latest models from Honda, Can-Am, and Polaris.</p>
    <%# <p>Perfect for off-road adventures and utility work.</p> %>
    <p>Explore our collection of new and used ATVs, all available at competitive prices.</p>
  </div>
  <%= render "shared/search_form" %>
</section>
<%= render "shared/categories" %>
<h1 class="suggested-bikes-title">Bikes & ATVs for Sale</h1>
<div class="bike-container" id="bikes-section" data-controller="scroll"
  data-scroll-target="bikeSection"
  <%= @search_performed ? '' : 'style="display: none;"' %>>
  <% @bikes.each do |bike| %>
    <div class="bike-card">
      <%= link_to bike_path(bike) do %>
        <div class="bike-image">
          <% if bike.photos.first.present? %>
            <%= image_tag bike.photos.first, height: 300, width: 400, crop: :fill, alt: bike.model %>
          <% else %>
            <%= image_tag 'san_francisco.jpg', height: 300, width: 400, crop: :fill, alt: 'Default bike image' %>
          <% end %>
        </div>

        <div class="bike-info">
          <h3 class="bike-title"><%= bike.model %></h3>
          <% if bike.category.name == "Electric" %>
            <p><strong>Make: </strong><%= bike.make %></p>
          <% else %>
            <p><strong>Make: </strong><%= bike.brand.name %></p>
          <% end %>
          <p><strong>Price: </strong><%= number_to_currency(bike.price) %></p>
          <p><strong>Engine: </strong><%= bike.engine_capacity %> CC</p>
        </div>
      <% end %>
    </div>
  <% end %>
  <% @e_bikes.each do |bike| %>
    <div class="bike-card">
      <%= link_to bike_path(bike) do %>
        <div class="bike-image">
          <% if bike.photos.first.present? %>
            <%= image_tag bike.photos.first, height: 300, width: 400, crop: :fill, alt: bike.model %>
          <% else %>
            <%= image_tag 'san_francisco.jpg', height: 300, width: 400, crop: :fill, alt: 'Default bike image' %>
          <% end %>
        </div>

        <div class="bike-info">
          <h3 class="bike-title"><%= bike.model %></h3>
          <% if bike.category.name == "Electric" %>
            <p><strong>Make: </strong><%= bike.make %></p>
          <% else %>
            <p><strong>Make: </strong><%= bike.brand.name %></p>
          <% end %>
          <p><strong>Price: </strong><%= number_to_currency(bike.price) %></p>
          <p><strong>Engine: </strong><%= bike.engine_capacity %> CC</p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<!-- Articles section -->
<%= render "shared/articles" %>
<!-- Reviews Section -->
<div class="container">
  <div class="bike-reviews">
    <h2>Reviews</h2>

    <% if @reviews.any? %>
      <%# Calculate the average rating and display it as stars %>
      <% average_rating = @reviews.average(:rating).to_f.round(1) %>
      <p>Average Rating:
        <% (1..5).each do |star| %>
          <i style="color: #ffcc00" class="fa stars <%= average_rating >= star ? 's' : 'r' %> fa-star"></i> <!-- filled or regular star -->
        <% end %>
        (<%= average_rating %> based on <%= @reviews.count %> reviews)
      </p>

      <% @reviews.each do |review| %>
        <div class="review">
          <p><strong><%= review.reviewer_name %></strong> - <%= review.rating %>/5</p>
          <p><%= review.content %></p>
          <%# Display rating as stars %>
          <p>
            <% (1..5).each do |star| %>
              <i style="color: #ffcc00" class="fa stars<%= review.rating >= star ? 's' : 'r' %> fa-star"></i> <!-- filled or regular star -->
            <% end %>
          </p>
        </div>
      <% end %>
    <% else %>
      <p>No reviews yet.</p>
    <% end %>
  </div>
</div>
<% if @scroll_to_bikes %>
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      // Scroll to the bikes section
      const bikesSection = document.getElementById('bikes-section');
      if (bikesSection) {
        bikesSection.scrollIntoView({ behavior: 'smooth' });
      }
      bikesSection.style.transition = 'background-color 0.5s';
    bikesSection.style.backgroundColor = '#fffae6'; // Highlight color
    setTimeout(() => {
      bikesSection.style.backgroundColor = ''; // Remove highlight
    }, 1500);
    });
  </script>
<% end %>

app/views/bikes/new.html.erb
<h2 class="form-title">Register a New Bike</h2>

<%= simple_form_for @bike,
    local: true,
    data: { controller: "loading", action: "submit->loading#showSpinner" },
    html: { class: "custom-bike-form" } do |form| %>
  <div class="form-group">
    <%= form.input :model, placeholder: "Enter bike model/Name", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :kilometers, placeholder: "Enter kilometers traveled", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :body, placeholder: "Enter purpose or type of bike", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :colour, placeholder: "Enter color", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :engine_capacity, placeholder: "Enter engine capacity in cc", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :last_modified, as: :date, label: false, placeholder: "Select last modified date" %>
  </div>
  <div class="form-group">
  <%= form.input :registration_status,
                  as: :select,
                  collection: Bike.registration_statuses.keys,
                  prompt: "Enter registration status",
                  label: false %>
  </div>

  <div class="form-group">
    <%= form.input :description, placeholder: "Enter a brief description", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :features, placeholder: "List features separated by commas", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :price, placeholder: "Enter price in currency", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :maximum_speed, placeholder: "Enter maximum speed in km/h", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :fuel_type, placeholder: "Enter fuel type (e.g., petrol, electric)", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :make, placeholder: "Enter Make", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :category_id, as: :select, collection: Category.all, prompt: "Select a Category", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :brand_id, as: :select, collection: Brand.all, prompt: "Select a Brand", label: false %>
  </div>
  <div class="form-group">
    <%= form.input :photos, as: :file, input_html: { multiple: true }, label: false %>
  </div>
  <div class="form-group submit-button">
    <%= form.button :submit, "Create Bike" %>
  </div>
  <span class="loader" data-loading-target="spinner" style="display: none;"></span>
<% end %>

app/views/bikes/show.html.erb
<!-- Main Image Section -->

<div class="bike-contain">
  <!-- Bike Slider Section -->
  <%# <div class="bike-slider">
  <div class="slider-container"> %>
  <div class="bike-main-content">
    <!-- Main Image Slider -->
    <div class="bike-main-image">
      <% content_for :title, "#{@bike.model} ATV for Sale | Affordable Off-Road Adventure" %>
      <% content_for :meta_description, "#{@bike.model} #{@bike.description.truncate(156)}" %>
      <% if @bike.photos.attached? %>
        <% @bike.photos.each_with_index do |photo, index| %>
          <div class="mySlides">
            <div class="numbertext">
              <i class="fa-solid fa-camera"></i><%= index + 1 %>/<%= @bike.photos.count %>
            </div>
            <%= cl_image_tag photo.key, alt: @bike.model, class: "main-image" %>
          </div>
        <% end %>
      <% end %>

      <!-- Navigation Buttons -->
      <div class="slider-nav">
        <a class="prev" onclick="plusSlides(-1)">❮</a>
        <a class="next" onclick="plusSlides(1)">❯</a>
      </div>
      <!-- Saved Bikes Section -->
    <div class="saved-bike">
      <% if user_signed_in? %>
        <%= button_to bike_saved_bike_path(@bike),
        method: :post,
        remote: true,
        class: "btn favorite-btn",
        data: { id: @bike.id } do %>
        <i class="fa-regular fa-heart"></i>
      <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "btn" do %>
          <i class="fa-regular fa-heart"></i>
        <% end %>
      <% end %>
    </div>
<div class="bike-gallery">
      <% if @bike.photos.attached? %>
        <div class="thumbnails">
          <% @bike.photos.each_with_index do |photo, index| %>
            <% next if index == 0 %> <!-- Skip the first image -->
            <%= cl_image_tag photo.key, height: 100, width: 100, crop: :fill, class: "thumbnail", onclick: "currentSlide(#{index + 1})" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

    </div>




    <!-- Bike Gallery -->


  <!-- Order Form Section -->
  <div class="bike-form">
    <%= simple_form_for [@bike, @order],
      local: true,
      data: { controller: "loading", action: "submit->loading#showSpinner" },
      html: { class: "custom-bike-form" } do |form| %>
      <div class="row">
        <h1 style="font-size: 1.5rem;"><i class="fa-solid fa-phone" style="color: green;"></i>  Contact the Dealer (341)223-3974</h1>
        <div class="col-8">
          <h1 class="bike-show-title"><%= @bike.model %> For Sale</h1>
          <h1 class="bike-show-title" ><%= number_to_currency(@bike.price) %></h1>
        </div>
      <div class="col-4">
        <%= image_tag "offer.jpg", height: 100, width: 350, crop: :fill %>
      </div>
      </div>
      <% if @order.errors.any? %>
        <div class="error-messages alert alert-danger">
          <h3>There were some errors with your order:</h3>
          <ul>
            <% @order.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :phone %>
        <%= form.number_field :phone, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :shipping_address %>
        <%= form.text_field :location, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :quantity %>
        <%= form.number_field :quantity, min: 1, class: "form-control" %>
      </div>

      <%= text_field_tag :nickname, nil, style: "display: none;", autocomplete: "off" %>

      <div class="form-group submit-button">
        <%= form.button :submit, "Request Purchase Info", class: "btn btn-dark text-white" %>
      </div>

    <% end %>
  </div>
</div>

<!-- Bike Information Section -->
<div class="bike-details">
  <div class="popularity-stats">
  <h2 class="stats-title"><i class="fa-solid fa-chart-line"></i> Popularity Stats</h2>
  <div class="stats-row">
    <div class="stats-item">
      <i class="fa-solid fa-eye"></i>
      <span><strong>Seen:</strong> <%= rand(30..100) %> times (last 30 days)</span>
    </div>
    <div class="stats-item">
      <i class="fa-solid fa-bookmark"></i>
      <span><strong>Saved:</strong> by <%= rand(2..10) %> people</span>
    </div>
    <div class="stats-item">
      <i class="fa-solid fa-tags"></i>
      <span><strong>Price Update:</strong> The price recently decreased by $<%= rand(1000..5000) %></span>
    </div>
  </div>
</div>

  <table class="mt-5">
    <tr>
      <td><strong>Category:</strong></td>
      <td><%= @bike.category.name %></td>
    </tr>
    <% if @bike.category.name == "Electric" %>
      <tr>
        <td><strong>Make:</strong></td>
        <td><%= @bike.make %></td>
      </tr>
    <% else %>
      <tr>
        <td><strong>Brand:</strong></td>
        <td><%= @bike.brand.name %></td>
      </tr>
    <% end %>
    <tr>
      <td><strong>Kilometers:</strong></td>
      <td><%= @bike.kilometers %> km</td>
    </tr>
    <tr>
      <td><strong>Purpose:</strong></td>
      <td><%= @bike.body %></td>
    </tr>
    <tr>
      <td><strong>Colour:</strong></td>
      <td><%= @bike.colour %></td>
    </tr>
    <% if @bike.category.name == "Electric" %>
      <tr>
      <td><strong>Engine Capacity:</strong></td>
      <td><%= @bike.engine_capacity %> W</td>
    </tr>
    <% else %>
      <tr>
      <td><strong>Engine Capacity:</strong></td>
      <td><%= @bike.engine_capacity %> cc</td>
    </tr>
    <% end %>
    <tr>
      <td><strong>Maximum Speed:</strong></td>
      <td><%= @bike.maximum_speed %> km/h</td>
    </tr>
    <tr>
      <td><strong>Fuel:</strong></td>
      <td><%= @bike.fuel_type %></td>
    </tr>
    <tr>
      <td><strong>Description:</strong></td>
      <td><%= @bike.description %></td>
    </tr>
  </table>
<h2 class="mt-5">Features</h2>
<p><%= @bike.features %></p>


<div>
  <%= link_to bikes_path, class: "back-link" do %>
    <i class="fas fa-arrow-left"></i> Back to Bikes
  <% end %>

  <% if current_user&.admin? %>
  <%= link_to edit_bike_path(@bike), class: "back-link" do %>
    <i class="fas fa-edit"></i> Edit Bike
  <% end %>

  <%= button_to bike_path(@bike), method: :delete, data: { confirm: 'Are you sure?' }, class: "back-link" do %>
    <i class="fas fa-trash-alt"></i> Delete
  <% end %>
<% end %>
</div>

</div>
<script>
let slideIndex = 1;
showSlides(slideIndex);

// Detect swipe gestures
let xDown = null;
let yDown = null;

document.getElementById("slider").addEventListener('touchstart', handleTouchStart, false);
document.getElementById("slider").addEventListener('touchmove', handleTouchMove, false);


let clickElements = document.querySelectorAll(".i");
clickElements.forEach(element => {
  element.addEventListener("click", () => {
    element.style.color = "red";
  });
});


function handleTouchStart(evt) {
  const firstTouch = evt.touches[0];
  xDown = firstTouch.clientX;
  yDown = firstTouch.clientY;
}

function handleTouchMove(evt) {
  if (!xDown || !yDown) {
    return;
  }

  let xUp = evt.touches[0].clientX;
  let yUp = evt.touches[0].clientY;

  let xDiff = xDown - xUp;
  let yDiff = yDown - yUp;

  if (Math.abs(xDiff) > Math.abs(yDiff)) { // Most significant movement
    if (xDiff > 0) {
      // Left swipe
      plusSlides(1);
    } else {
      // Right swipe
      plusSlides(-1);
    }
  }
  // Reset values
  xDown = null;
  yDown = null;
}

// Function to change slide
function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  slides[slideIndex-1].style.display = "block";
}

</script>